hangman_api_hello_world:
    path:     /hello/world
    defaults: { _controller: HangmanApiBundle:HelloWorld:helloWorld }
    methods:  [GET]
games:
    path:     /games/{character}
    defaults: { _controller: HangmanApiBundle:Games:games, character:0 }
    methods:  [GET|POST]
    requirements:
      character: "[a-z]"